import type { TeamPlayer } from '../../context/GameContext';

const defaultPlayers = (names?: string[]): TeamPlayer[] => {
  const nameAt = (i: number) => names?.[i]?.trim() || `Player ${i + 1}`;

  return [
    {
      index: 0,
      name: nameAt(0),
      runs: 0,
      wicketsTaken: 0,
      currentStriker: true,
      currentNonStriker: false,
      currentBowler: false,
      allActions: [],
      onTheCrease: true,
      status: 'Not out',
      methodOfWicket: null,
      oversBowled: 0,
      runsConceded: 0
    },
    {
      index: 1,
      name: nameAt(1),
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: true,
      currentBowler: false,
      allActions: [],
      onTheCrease: true,
      status: 'Not out',
      methodOfWicket: null,
      oversBowled: 0,
      runsConceded: 0
    },
    {
      index: 2,
      name: nameAt(2),
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: false,
      currentBowler: false,
      allActions: [],
      onTheCrease: false,
      status: 'Not out',
      methodOfWicket: null,
      oversBowled: 0,
      runsConceded: 0
    },
    {
      index: 3,
      name: nameAt(3),
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: false,
      currentBowler: false,
      allActions: [],
      onTheCrease: false,
      status: 'Not out',
      methodOfWicket: null,
      oversBowled: 0,
      runsConceded: 0
    },
    {
      index: 4,
      name: nameAt(4),
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: false,
      currentBowler: false,
      allActions: [],
      onTheCrease: false,
      status: 'Not out',
      methodOfWicket: null,
      oversBowled: 0,
      runsConceded: 0
    },
    {
      index: 5,
      name: nameAt(5),
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: false,
      currentBowler: false,
      allActions: [],
      onTheCrease: false,
      status: 'Not out',
      methodOfWicket: null,
      oversBowled: 0,
      runsConceded: 0
    },
    {
      index: 6,
      name: nameAt(6),
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: false,
      currentBowler: false,
      allActions: [],
      onTheCrease: false,
      status: 'Not out',
      methodOfWicket: null,
      oversBowled: 0,
      runsConceded: 0
    },
    {
      index: 7,
      name: nameAt(7),
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: false,
      currentBowler: false,
      allActions: [],
      onTheCrease: false,
      status: 'Not out',
      methodOfWicket: null,
      oversBowled: 0,
      runsConceded: 0
    },
    {
      index: 8,
      name: nameAt(8),
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: false,
      currentBowler: false,
      allActions: [],
      onTheCrease: false,
      status: 'Not out',
      methodOfWicket: null,
      oversBowled: 0,
      runsConceded: 0
    },
    {
      index: 9,
      name: nameAt(9),
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: false,
      currentBowler: false,
      allActions: [],
      onTheCrease: false,
      status: 'Not out',
      methodOfWicket: null,
      oversBowled: 0,
      runsConceded: 0
    },
    {
      index: 10,
      name: nameAt(10),
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: false,
      currentBowler: false,
      allActions: [],
      onTheCrease: false,
      status: 'Not out',
      methodOfWicket: null,
      oversBowled: 0,
      runsConceded: 0
    }
  ];
};

export default defaultPlayers;
