const defaultPlayers = () => {
  return [
    {
      index: 0,
      name: 'Player 1',
      runs: 0,
      wicketsTaken: 0,
      currentStriker: true,
      currentNonStriker: false,
      currentBowler: false,
      isOut: false,
      allActions: [],
      onTheCrease: true,
      status: 'Not out',
      methodOfWicket: null
    },
    {
      index: 1,
      name: 'Player 2',
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: true,
      currentBowler: false,
      isOut: false,
      allActions: [],
      onTheCrease: true,
      status: 'Not out',
      methodOfWicket: null
    },
    {
      index: 2,
      name: 'Player 3',
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: false,
      currentBowler: false,
      isOut: false,
      allActions: [],
      onTheCrease: false,
      status: 'Not out',
      methodOfWicket: null
    },
    {
      index: 3,
      name: 'Player 4',
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: false,
      currentBowler: false,
      isOut: false,
      allActions: [],
      onTheCrease: false,
      status: 'Not out',
      methodOfWicket: null
    },
    {
      index: 4,
      name: 'Player 5',
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: false,
      currentBowler: false,
      isOut: false,
      allActions: [],
      onTheCrease: false,
      status: 'Not out',
      methodOfWicket: null
    },
    {
      index: 5,
      name: 'Player 6',
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: false,
      currentBowler: false,
      isOut: false,
      allActions: [],
      onTheCrease: false,
      status: 'Not out',
      methodOfWicket: null
    },
    {
      index: 6,
      name: 'Player 7',
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: false,
      currentBowler: false,
      isOut: false,
      allActions: [],
      onTheCrease: false,
      status: 'Not out',
      methodOfWicket: null
    },
    {
      index: 7,
      name: 'Player 8',
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: false,
      currentBowler: false,
      isOut: false,
      allActions: [],
      onTheCrease: false,
      status: 'Not out',
      methodOfWicket: null
    },
    {
      index: 8,
      name: 'Player 9',
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: false,
      currentBowler: false,
      isOut: false,
      allActions: [],
      onTheCrease: false,
      status: 'Not out',
      methodOfWicket: null
    },
    {
      index: 9,
      name: 'Player 10',
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: false,
      currentBowler: false,
      isOut: false,
      allActions: [],
      onTheCrease: false,
      status: 'Not out',
      methodOfWicket: null
    },
    {
      index: 10,
      name: 'Player 11',
      runs: 0,
      wicketsTaken: 0,
      currentStriker: false,
      currentNonStriker: false,
      currentBowler: false,
      isOut: false,
      allActions: [],
      onTheCrease: false,
      status: 'Not out',
      methodOfWicket: null
    }
  ];
};

export default defaultPlayers;
